docs: Fix CONTRIBUTING.md to avoid error when running cargo build (#145)
After a fresh checkout `melos bs` must be run first otherwise when
running `cargo build -r` it fails for a missing pubspec.lock:

```
error: failed to run custom build command for `embedded_milli v0.0.0 ([redacted]/code/dart/mimir/packages/mimir/native)`

Caused by:
  process didn't exit successfully: `[redacted]/code/dart/mimir/target/release/build/embedded_milli-193bf6019fe04397/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=src/api.rs

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: missing pubspec.lock in [redacted]/code/dart/mimir/packages/mimir/native/..', packages/mimir/native/build.rs:32:43
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```